// Generated by https://quicktype.io


export interface PosProduct {
  name: string;
  owner: string;
  creation: string;
  modified: string;
  modified_by: string;
  docstatus: number;
  idx: number;
  customer_id: string;
  item_id: string;
  item_name: string;
  level: number;
  price: number;
  doctype: string;
  isInCart: boolean;
  quantityInCart: number;
  item_image?: string;
}
